### ISSUE TITLE
No module named 'comments_cache'

### ISSUE THREAD

**Issue by trib0r3** [Cisco-Talos/GhIDA#12]
Hi, I have a problem with running this problem, because of weird python import issue:

```
C:\Program Files\IDA Pro 7.4\plugins\ghida.py: No module named 'comments_cache'
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_idaapi.py", line 593, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.4/plugins/ghida.py", line 37, in <module>
    import ghida_plugin as gl
  File "C:/Program Files/IDA Pro 7.4/plugins\ghida_plugin\__init__.py", line 26, in <module>
    from comments_cache import *
ModuleNotFoundError: No module named 'comments_cache'
```

I know that:
- module exists,
- can be imported if we are running python shell in `ghida_plugin` dir, but not from parent directory where `ghida.py` is located
- I'm guessing is somehow related how `__init__.py` works :/

**Comment by trib0r3** [comment]
Ok, I mamaged to solve this issue, I will create PR after I will port GHIDA to python3

**Comment by x-remix-x** [comment]
Having this issue pop up again with IDA 7.6

```
C:\Program Files\IDA Pro 7.6\plugins\ghida.py: No module named 'comments_cache'
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.6\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.6/plugins/ghida.py", line 37, in <module>
    import ghida_plugin as gl
  File "C:/Program Files/IDA Pro 7.6/plugins\ghida_plugin\__init__.py", line 26, in <module>
    from comments_cache import *
ModuleNotFoundError: No module named 'comments_cache'
```

**Comment by joshterrill** [comment]
It looks like the fixes are in this PR: https://github.com/Cisco-Talos/GhIDA/pull/13 but it got closed by @trib0r3 and never had a chance to be merged. I can confirm that with python3, these changes DO appear to work fine.
